// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--rc3
// source: internal/proto/sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncResponse_SyncStatus int32

const (
	SyncResponse_SYNCED       SyncResponse_SyncStatus = 0
	SyncResponse_CONFLICT     SyncResponse_SyncStatus = 1
	SyncResponse_NEEDS_UPDATE SyncResponse_SyncStatus = 2
	SyncResponse_ERROR        SyncResponse_SyncStatus = 3
)

// Enum value maps for SyncResponse_SyncStatus.
var (
	SyncResponse_SyncStatus_name = map[int32]string{
		0: "SYNCED",
		1: "CONFLICT",
		2: "NEEDS_UPDATE",
		3: "ERROR",
	}
	SyncResponse_SyncStatus_value = map[string]int32{
		"SYNCED":       0,
		"CONFLICT":     1,
		"NEEDS_UPDATE": 2,
		"ERROR":        3,
	}
)

func (x SyncResponse_SyncStatus) Enum() *SyncResponse_SyncStatus {
	p := new(SyncResponse_SyncStatus)
	*p = x
	return p
}

func (x SyncResponse_SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncResponse_SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_sync_proto_enumTypes[0].Descriptor()
}

func (SyncResponse_SyncStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_sync_proto_enumTypes[0]
}

func (x SyncResponse_SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncResponse_SyncStatus.Descriptor instead.
func (SyncResponse_SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{1, 0}
}

type FileChangeEvent_ChangeType int32

const (
	FileChangeEvent_CREATED  FileChangeEvent_ChangeType = 0
	FileChangeEvent_MODIFIED FileChangeEvent_ChangeType = 1
	FileChangeEvent_DELETED  FileChangeEvent_ChangeType = 2
	FileChangeEvent_RENAMED  FileChangeEvent_ChangeType = 3
)

// Enum value maps for FileChangeEvent_ChangeType.
var (
	FileChangeEvent_ChangeType_name = map[int32]string{
		0: "CREATED",
		1: "MODIFIED",
		2: "DELETED",
		3: "RENAMED",
	}
	FileChangeEvent_ChangeType_value = map[string]int32{
		"CREATED":  0,
		"MODIFIED": 1,
		"DELETED":  2,
		"RENAMED":  3,
	}
)

func (x FileChangeEvent_ChangeType) Enum() *FileChangeEvent_ChangeType {
	p := new(FileChangeEvent_ChangeType)
	*p = x
	return p
}

func (x FileChangeEvent_ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileChangeEvent_ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_sync_proto_enumTypes[1].Descriptor()
}

func (FileChangeEvent_ChangeType) Type() protoreflect.EnumType {
	return &file_internal_proto_sync_proto_enumTypes[1]
}

func (x FileChangeEvent_ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileChangeEvent_ChangeType.Descriptor instead.
func (FileChangeEvent_ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{8, 0}
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	FileHash      string                 `protobuf:"bytes,4,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	LastModified  string                 `protobuf:"bytes,6,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_proto_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *SyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SyncRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *SyncRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SyncRequest) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

type SyncResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Status          SyncResponse_SyncStatus `protobuf:"varint,1,opt,name=status,proto3,enum=proto.SyncResponse_SyncStatus" json:"status,omitempty"`
	Message         string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatestVersionId string                  `protobuf:"bytes,3,opt,name=latest_version_id,json=latestVersionId,proto3" json:"latest_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_proto_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetStatus() SyncResponse_SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncResponse_SYNCED
}

func (x *SyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncResponse) GetLatestVersionId() string {
	if x != nil {
		return x.LatestVersionId
	}
	return ""
}

type FileVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileVersionRequest) Reset() {
	*x = FileVersionRequest{}
	mi := &file_internal_proto_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileVersionRequest) ProtoMessage() {}

func (x *FileVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileVersionRequest.ProtoReflect.Descriptor instead.
func (*FileVersionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{2}
}

func (x *FileVersionRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileVersionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FileVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     string                 `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileVersion) Reset() {
	*x = FileVersion{}
	mi := &file_internal_proto_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileVersion) ProtoMessage() {}

func (x *FileVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileVersion.ProtoReflect.Descriptor instead.
func (*FileVersion) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{3}
}

func (x *FileVersion) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *FileVersion) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FileVersion) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FileVersion) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileVersion) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type FileVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*FileVersion         `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileVersionResponse) Reset() {
	*x = FileVersionResponse{}
	mi := &file_internal_proto_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileVersionResponse) ProtoMessage() {}

func (x *FileVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileVersionResponse.ProtoReflect.Descriptor instead.
func (*FileVersionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{4}
}

func (x *FileVersionResponse) GetVersions() []*FileVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ConflictResolutionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FileId           string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WinningVersionId string                 `protobuf:"bytes,3,opt,name=winning_version_id,json=winningVersionId,proto3" json:"winning_version_id,omitempty"`
	LosingVersionIds []string               `protobuf:"bytes,4,rep,name=losing_version_ids,json=losingVersionIds,proto3" json:"losing_version_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConflictResolutionRequest) Reset() {
	*x = ConflictResolutionRequest{}
	mi := &file_internal_proto_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictResolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictResolutionRequest) ProtoMessage() {}

func (x *ConflictResolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictResolutionRequest.ProtoReflect.Descriptor instead.
func (*ConflictResolutionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ConflictResolutionRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ConflictResolutionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConflictResolutionRequest) GetWinningVersionId() string {
	if x != nil {
		return x.WinningVersionId
	}
	return ""
}

func (x *ConflictResolutionRequest) GetLosingVersionIds() []string {
	if x != nil {
		return x.LosingVersionIds
	}
	return nil
}

type ConflictResolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewVersionId  string                 `protobuf:"bytes,3,opt,name=new_version_id,json=newVersionId,proto3" json:"new_version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictResolutionResponse) Reset() {
	*x = ConflictResolutionResponse{}
	mi := &file_internal_proto_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictResolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictResolutionResponse) ProtoMessage() {}

func (x *ConflictResolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictResolutionResponse.ProtoReflect.Descriptor instead.
func (*ConflictResolutionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{6}
}

func (x *ConflictResolutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConflictResolutionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConflictResolutionResponse) GetNewVersionId() string {
	if x != nil {
		return x.NewVersionId
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	FolderPaths   []string               `protobuf:"bytes,3,rep,name=folder_paths,json=folderPaths,proto3" json:"folder_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_internal_proto_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WatchRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *WatchRequest) GetFolderPaths() []string {
	if x != nil {
		return x.FolderPaths
	}
	return nil
}

type FileChangeEvent struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	FileId        string                     `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FilePath      string                     `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ChangeType    FileChangeEvent_ChangeType `protobuf:"varint,3,opt,name=change_type,json=changeType,proto3,enum=proto.FileChangeEvent_ChangeType" json:"change_type,omitempty"`
	Timestamp     string                     `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeviceId      string                     `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	VersionId     string                     `protobuf:"bytes,6,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChangeEvent) Reset() {
	*x = FileChangeEvent{}
	mi := &file_internal_proto_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChangeEvent) ProtoMessage() {}

func (x *FileChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChangeEvent.ProtoReflect.Descriptor instead.
func (*FileChangeEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{8}
}

func (x *FileChangeEvent) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileChangeEvent) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileChangeEvent) GetChangeType() FileChangeEvent_ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return FileChangeEvent_CREATED
}

func (x *FileChangeEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FileChangeEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FileChangeEvent) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

var File_internal_proto_sync_proto protoreflect.FileDescriptor

const file_internal_proto_sync_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/sync.proto\x12\x05proto\"\xbb\x01\n" +
	"\vSyncRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tfile_hash\x18\x04 \x01(\tR\bfileHash\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12#\n" +
	"\rlast_modified\x18\x06 \x01(\tR\flastModified\"\xd1\x01\n" +
	"\fSyncResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.proto.SyncResponse.SyncStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11latest_version_id\x18\x03 \x01(\tR\x0flatestVersionId\"C\n" +
	"\n" +
	"SyncStatus\x12\n" +
	"\n" +
	"\x06SYNCED\x10\x00\x12\f\n" +
	"\bCONFLICT\x10\x01\x12\x10\n" +
	"\fNEEDS_UPDATE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"F\n" +
	"\x12FileVersionRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x90\x01\n" +
	"\vFileVersion\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\"E\n" +
	"\x13FileVersionResponse\x12.\n" +
	"\bversions\x18\x01 \x03(\v2\x12.proto.FileVersionR\bversions\"\xa9\x01\n" +
	"\x19ConflictResolutionRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x12winning_version_id\x18\x03 \x01(\tR\x10winningVersionId\x12,\n" +
	"\x12losing_version_ids\x18\x04 \x03(\tR\x10losingVersionIds\"v\n" +
	"\x1aConflictResolutionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0enew_version_id\x18\x03 \x01(\tR\fnewVersionId\"g\n" +
	"\fWatchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\ffolder_paths\x18\x03 \x03(\tR\vfolderPaths\"\xa8\x02\n" +
	"\x0fFileChangeEvent\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12B\n" +
	"\vchange_type\x18\x03 \x01(\x0e2!.proto.FileChangeEvent.ChangeTypeR\n" +
	"changeType\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x06 \x01(\tR\tversionId\"A\n" +
	"\n" +
	"ChangeType\x12\v\n" +
	"\aCREATED\x10\x00\x12\f\n" +
	"\bMODIFIED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02\x12\v\n" +
	"\aRENAMED\x10\x032\xa7\x02\n" +
	"\vSyncService\x123\n" +
	"\bSyncFile\x12\x12.proto.SyncRequest\x1a\x13.proto.SyncResponse\x12H\n" +
	"\x0fGetFileVersions\x12\x19.proto.FileVersionRequest\x1a\x1a.proto.FileVersionResponse\x12V\n" +
	"\x0fResolveConflict\x12 .proto.ConflictResolutionRequest\x1a!.proto.ConflictResolutionResponse\x12A\n" +
	"\x10WatchFileChanges\x12\x13.proto.WatchRequest\x1a\x16.proto.FileChangeEvent0\x01BPZNgithub.com/Shubham-Thakur06/go-distributed-file-syncing-service/internal/protob\x06proto3"

var (
	file_internal_proto_sync_proto_rawDescOnce sync.Once
	file_internal_proto_sync_proto_rawDescData []byte
)

func file_internal_proto_sync_proto_rawDescGZIP() []byte {
	file_internal_proto_sync_proto_rawDescOnce.Do(func() {
		file_internal_proto_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_sync_proto_rawDesc), len(file_internal_proto_sync_proto_rawDesc)))
	})
	return file_internal_proto_sync_proto_rawDescData
}

var file_internal_proto_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_proto_sync_proto_goTypes = []any{
	(SyncResponse_SyncStatus)(0),       // 0: proto.SyncResponse.SyncStatus
	(FileChangeEvent_ChangeType)(0),    // 1: proto.FileChangeEvent.ChangeType
	(*SyncRequest)(nil),                // 2: proto.SyncRequest
	(*SyncResponse)(nil),               // 3: proto.SyncResponse
	(*FileVersionRequest)(nil),         // 4: proto.FileVersionRequest
	(*FileVersion)(nil),                // 5: proto.FileVersion
	(*FileVersionResponse)(nil),        // 6: proto.FileVersionResponse
	(*ConflictResolutionRequest)(nil),  // 7: proto.ConflictResolutionRequest
	(*ConflictResolutionResponse)(nil), // 8: proto.ConflictResolutionResponse
	(*WatchRequest)(nil),               // 9: proto.WatchRequest
	(*FileChangeEvent)(nil),            // 10: proto.FileChangeEvent
}
var file_internal_proto_sync_proto_depIdxs = []int32{
	0,  // 0: proto.SyncResponse.status:type_name -> proto.SyncResponse.SyncStatus
	5,  // 1: proto.FileVersionResponse.versions:type_name -> proto.FileVersion
	1,  // 2: proto.FileChangeEvent.change_type:type_name -> proto.FileChangeEvent.ChangeType
	2,  // 3: proto.SyncService.SyncFile:input_type -> proto.SyncRequest
	4,  // 4: proto.SyncService.GetFileVersions:input_type -> proto.FileVersionRequest
	7,  // 5: proto.SyncService.ResolveConflict:input_type -> proto.ConflictResolutionRequest
	9,  // 6: proto.SyncService.WatchFileChanges:input_type -> proto.WatchRequest
	3,  // 7: proto.SyncService.SyncFile:output_type -> proto.SyncResponse
	6,  // 8: proto.SyncService.GetFileVersions:output_type -> proto.FileVersionResponse
	8,  // 9: proto.SyncService.ResolveConflict:output_type -> proto.ConflictResolutionResponse
	10, // 10: proto.SyncService.WatchFileChanges:output_type -> proto.FileChangeEvent
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_sync_proto_init() }
func file_internal_proto_sync_proto_init() {
	if File_internal_proto_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_sync_proto_rawDesc), len(file_internal_proto_sync_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_sync_proto_goTypes,
		DependencyIndexes: file_internal_proto_sync_proto_depIdxs,
		EnumInfos:         file_internal_proto_sync_proto_enumTypes,
		MessageInfos:      file_internal_proto_sync_proto_msgTypes,
	}.Build()
	File_internal_proto_sync_proto = out.File
	file_internal_proto_sync_proto_goTypes = nil
	file_internal_proto_sync_proto_depIdxs = nil
}
